# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 872cc44a5b97ace2a09088a646a1377e7bfa98f907892651cc6a008f9c2ae229fd46a1dad1a36ace82c32f86ab8cf620396d8dc65c0a4b1ba13d56baf5d46f9c

test:
  secret_key_base: 6d1712111199302885b09d1b823edcb0779a7124781084a1b7c3793d44c42d1b8242b1938e7010b5761a4c78c7f7af83fec1c8f031abf305e9fc9bf6e30dc354

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
